# Generated by Django 4.2.7 on 2025-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name="Ta'rif")),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Rasm')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': "Biz haqimizda ma'lumotlar",
            },
        ),
    ]
