# Generated by Django 5.2.6 on 2025-09-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sertifikat nomi')),
                ('description', models.TextField(verbose_name="Ta'rif")),
                ('certificate_type', models.CharField(choices=[('completion', 'Kursni tugatish sertifikati'), ('achievement', 'Yutuq sertifikati'), ('participation', 'Ishtirok sertifikati'), ('professional', 'Professional sertifikat')], default='completion', max_length=20, verbose_name='Sertifikat turi')),
                ('requirements', models.TextField(verbose_name='Olish shartlari')),
                ('validity_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Amal qilish muddati')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Sertifikat namunasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Talaba ismi')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('issue_date', models.DateField(verbose_name='Berilgan sana')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Sertifikat raqami')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate', verbose_name='Sertifikat')),
            ],
            options={
                'verbose_name': 'Talaba sertifikati',
                'verbose_name_plural': 'Talaba sertifikatlari',
                'ordering': ['-issue_date'],
            },
        ),
    ]
