# Generated by Django 5.2.6 on 2025-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh.')),
                ('specialization', models.CharField(max_length=200, verbose_name='Mutaxassislik')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Tajriba yillari')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialists/', verbose_name='Surat')),
                ('bio', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mutaxassis',
                'verbose_name_plural': 'Mutaxassislar',
                'ordering': ['full_name'],
            },
        ),
    ]
