# Generated by Django 5.2.6 on 2025-09-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Yo'nalish nomi")),
                ('description', models.TextField(verbose_name="Ta'rif")),
                ('image', models.ImageField(blank=True, null=True, upload_to='directions/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mutaxassislik nomi')),
                ('description', models.TextField(verbose_name="Ta'rif")),
                ('duration', models.CharField(max_length=100, verbose_name='Davomiyligi')),
                ('requirements', models.TextField(verbose_name='Kirish talablari')),
                ('career_prospects', models.TextField(verbose_name='Karyera imkoniyatlari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='programs.direction', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Reja nomi')),
                ('plan_type', models.CharField(choices=[('annual', 'Yillik reja'), ('semester', 'Semestr rejasi'), ('monthly', 'Oylik reja'), ('weekly', 'Haftalik reja')], default='semester', max_length=20, verbose_name='Reja turi')),
                ('academic_year', models.CharField(help_text='Masalan: 2024-2025', max_length=20, verbose_name="O'quv yili")),
                ('semester', models.PositiveIntegerField(blank=True, null=True, verbose_name='Semestr raqami')),
                ('description', models.TextField(verbose_name="Ta'rif")),
                ('file', models.FileField(blank=True, null=True, upload_to='study_plans/', verbose_name='Reja fayli (PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='programs.specialization', verbose_name='Mutaxassislik')),
            ],
            options={
                'verbose_name': "O'quv rejasi",
                'verbose_name_plural': "O'quv rejalari",
                'ordering': ['-academic_year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fan nomi')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fan kodi')),
                ('credits', models.PositiveIntegerField(verbose_name='Kredit soatlari')),
                ('lecture_hours', models.PositiveIntegerField(default=0, verbose_name="Ma'ruza soatlari")),
                ('practical_hours', models.PositiveIntegerField(default=0, verbose_name="Amaliy mashg'ulot soatlari")),
                ('laboratory_hours', models.PositiveIntegerField(default=0, verbose_name='Laboratoriya soatlari')),
                ('independent_hours', models.PositiveIntegerField(default=0, verbose_name='Mustaqil ish soatlari')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name="Oldindan o'rganilishi kerak fanlar")),
                ('description', models.TextField(verbose_name="Fan haqida ma'lumot")),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib raqami')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='programs.studyplan', verbose_name="O'quv rejasi")),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
