# Generated by Django 5.2.6 on 2025-09-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim nomi')),
                ('requirements', models.TextField(verbose_name='Talablar')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ish haqi')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Murojaat email manzili')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
